- hosts: tag_btcpie_true
  vars:
    home_dir: /Users/drew
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "{{home_dir}}/.ssh/btcpie2.pem"
    remote_dir: "/home/{{ansible_ssh_user}}"
    local_aws_dir: "{{home_dir}}/.aws"
    local_keyfile: "{{home_dir}}/.ssh/crednetials"
    remote_keyfile: "{{remote_dir}}/.ssh/credentials"
  tasks:
    - name: Deploy market-services files from Bitbucket repository
      git: repo=https://github.com/DrawnWren/market-service.git dest={{remote_dir}}/market-service accept_hostkey=true
      tags: git

    - name: Install service dependencies
      npm: 
        path: "{{remote_dir}}/market-service"

    - name: Refresh the pm2 service
      command: pm2 restart main

